---
title: "Clinicians-who-code course - module 1 - Where is the on switch?"
author: "Clinicians who code"
format: revealjs
logo: /images/cwc-logo.png
css: /slides.css
title-slide-attributes:
    data-background-video: "/images/waves-on-beach.mp4"
    data-background-video-loop: true
---


## Introduction {background-image="/images/welcome-sign.jpg" background-opacity="0.4"}

* Welcome and thank you for joining our course.
* We hope you enjoy the course and find it helpful.
* There are plans for further, more advanced courses, in the near future.
* Please provide feedback at the end of the course, so we can help improve things further.


## The coding environment {background-image="/images/bamboo-woods.jpg" background-opacity="0.2"}

* We will explore the development (teaching) environment.
* Get you connected to the development environment.
* Get you running some common command line functions in `Lession 1`.


## Python Basics {.smaller}

* How do we communicate with computers.
* Introduction to the python programming language.
* Learn about:
    * Syntax
    * Variables
    * Operators
    * Control flow
    * Functions
    * Error handling
* Then get you programming in `Lesson 2`.


## Why learn to code? {background-image="/images/why.jpg" background-opacity="0.3"}

* We learn biology and anatomy at university to understand and practice clinical medicine, why not the base subject to understand and practice digital medicine?
* Of course not all clinicians should be expected to have extensive knowledge in coding and digital health; that would take clinicians away from the front line, and also clinicians are expensive coders.
* However, having a small number of subject matter experts in both disciplines can be highly advantageous to implementing better and safer digital health projects.


## How can you use your coding skills in health care?

* Data analytics
* Building apps
* Data transfer
* Automate routine tasks
* Help lead a software development team with knowledge of both digital and clinical aspects.


* Indeed anything digital

## Tutor groups {background-image="/images/teacher-and-blackboard.jpg" background-opacity="0.6"}

* Has everyone been placed in a tutor group?

## Off we go to the shell {background-image="/images/horses-galloping.jpg" background-opacity="0.6"}
